# Generated by Django 2.2.4 on 2020-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='notes go here', max_length=255),
            preserve_default=False,
        ),
    ]
